### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by FAXTROT** [0or1-ML/house_price_kaggle_competition#1]
We need to find a way to exchange messages withing this project. Possible solutions : telegram channel, Slack.

**Comment by AAgzamov** [comment]
Lets create telegram channel for that.

**Comment by shkhryr** [comment]
Or we may use Discord for discussion and meetings related to projects. It would be more relevant, so we don't split up into small groups.

**Comment by AAgzamov** [comment]
> Or we may use Discord for discussion and meetings related to projects. It would be more relevant, so we don't split up into small groups.

I am fine with that.

**Comment by FAXTROT** [comment]
I am new in Discord, so @ShakhriyorKh could you please create chat/room/group, i do not know how is it called in Discord ?
